# Generated by Django 6.1 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='movie_list',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.movie'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
