# Generated by Django 6.1 on 2026-08-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appuser_movie_list_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('genres', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='movie_list',
        ),
        migrations.AddField(
            model_name='appuser',
            name='spotify_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='core.appuser')),
                ('songs', models.ManyToManyField(related_name='playlists', to='core.song')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
