# Generated by Django 6.1 on 2026-08-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_song_remove_appuser_movie_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='spotify_connected',
        ),
        migrations.CreateModel(
            name='SpotifyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True)),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_account', to='core.appuser')),
            ],
        ),
    ]
