# Generated by Django 6.1 on 2026-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_appuser_spotify_connected_spotifyaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='spotify_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
