# Generated by Django 6.1 on 2026-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_spotifyaccount_spotify_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='country',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
