# Generated by Django 6.1 on 2026-08-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_spotifyaccount_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
