# Generated by Django 6.1 on 2026-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_spotifyaccount_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
    ]
