# Generated by Django 6.1 on 2026-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_playlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='spotify_user',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
