# Generated by Django 6.1 on 2026-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_user_playlist_spotify_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
