# Generated by Django 6.1 on 2026-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
