# Generated by Django 6.1 on 2026-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_song_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
    ]
